# Generated by Django 2.2.5 on 2020-01-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20200107_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('AIRPORT', 'Airport'), ('CUSTOMS', 'Customs'), ('SHIPPING', 'Shipping'), ('TRANSPORT', 'Transport'), ('PROVIDERS', 'Providers')], default='Contacto-Local', max_length=100),
        ),
    ]
