# Generated by Django 2.2.5 on 2020-01-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_auto_20200108_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('AIRPORT', 'Airport'), ('CUSTOMS', 'Customs'), ('SHIPPING', 'Shipping'), ('TRANSPORT', 'Transport'), ('PROVIDERS', 'Providers'), ('ACCOMODATION', 'Hotels/Accomodation'), ('ALE', 'ALE Staff')], default='Providers', max_length=100),
        ),
    ]
