# Generated by Django 2.2.5 on 2020-01-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0009_auto_20200111_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='primary_phone',
        ),
    ]
