# Generated by Django 2.2.5 on 2020-01-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0010_auto_20200111_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitrep',
            options={'verbose_name': 'Sitrep', 'verbose_name_plural': 'Sitreps'},
        ),
    ]
