# Generated by Django 2.2.5 on 2020-01-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0011_auto_20200115_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='No email provided', max_length=100, verbose_name='Email'),
        ),
    ]
